loopback_users.guest = false
log.file.level = info
log.dir = /var/log/rabbitmq
log.file = rabbit.log
log.exchange = false
log.queue.level = info

collect_statistics = fine
collect_statistics_interval = 10000

vm_memory_high_watermark.absolute = 1GB
disk_free_limit.absolute = 1GB